PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE android_metadata (locale TEXT);
INSERT INTO android_metadata VALUES('en_US');
CREATE TABLE room_master_table (id INTEGER PRIMARY KEY,identity_hash TEXT);
INSERT INTO room_master_table VALUES(42,'13180d2e1fdc57604eca75c30c927962');
CREATE TABLE `user` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `first_name` TEXT, `last_name` TEXT, `email` TEXT, `password` TEXT NOT NULL);
INSERT INTO user VALUES(1,'Binu','Simon','Binu@gmail.com','binu');
CREATE TABLE `timetable` (`table_id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL DEFAULT 0, `day_of_week` TEXT NOT NULL DEFAULT 'MoN', `start_time` TEXT NOT NULL DEFAULT '09:00 AM', `end_time` TEXT NOT NULL DEFAULT '05:00 PM', `period` TEXT NOT NULL DEFAULT '11111', `programs_id` INTEGER NOT NULL DEFAULT 1, `semester_id` INTEGER NOT NULL DEFAULT 1, `subject_id` INTEGER NOT NULL DEFAULT 1, `instructor_id` INTEGER NOT NULL DEFAULT 1, `break_id` INTEGER DEFAULT 0, FOREIGN KEY(`subject_id`) REFERENCES `subjects`(`subject_id`) ON UPDATE NO ACTION ON DELETE SET NULL , FOREIGN KEY(`instructor_id`) REFERENCES `instructors`(`instructor_id`) ON UPDATE NO ACTION ON DELETE SET NULL , FOREIGN KEY(`break_id`) REFERENCES `breaks`(`break_id`) ON UPDATE NO ACTION ON DELETE SET NULL , FOREIGN KEY(`programs_id`) REFERENCES `programs`(`programs_id`) ON UPDATE NO ACTION ON DELETE SET NULL , FOREIGN KEY(`semester_id`) REFERENCES `semesters`(`semester_id`) ON UPDATE NO ACTION ON DELETE SET NULL );
INSERT INTO timetable VALUES(1,'Monday','9.00 AM','10.00 AM','1',1,3,3,1,1);
CREATE TABLE `subjects` (`subject_id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `subject_code` TEXT NOT NULL DEFAULT '23-493-', `subject_name` TEXT NOT NULL);
INSERT INTO subjects VALUES(1,'23-493-0201','PROJECT MANAGEMENT ');
INSERT INTO subjects VALUES(2,'23-493-0202','Android App Development - Kotlin & XML');
INSERT INTO subjects VALUES(3,'23-493-0203','Android App Development - JetPack Compose');
INSERT INTO subjects VALUES(4,'23-493-0204','CLOUD AND ADVANCED TECHNOLOGIES');
INSERT INTO subjects VALUES(5,'23-493-0205','Elective – I - Flutter for Beginners');
INSERT INTO subjects VALUES(6,'23-493-0206','Elective – II - Communicative English (Inter Dept)');
INSERT INTO subjects VALUES(7,'23-493-0207','SOFTWARE LAB-II (ANDROID & CLOUD)');
INSERT INTO subjects VALUES(8,'23-493-0208','INTERNSHIP I – ANDROID/WEB APP DEVELOPMENT');
CREATE TABLE `instructors` (`instructor_id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `instructor_name` TEXT NOT NULL);
INSERT INTO instructors VALUES(1,'Mr Vinu Varghese V.V');
INSERT INTO instructors VALUES(2,'Ms Suji Jose');
INSERT INTO instructors VALUES(3,'Mr Rishin Heb');
INSERT INTO instructors VALUES(4,'Mr Pradeep M');
CREATE TABLE `semesters` (`semester_id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `semester_name` TEXT NOT NULL);
INSERT INTO semesters VALUES(1,'Sem 1');
INSERT INTO semesters VALUES(2,'Sem 2');
INSERT INTO semesters VALUES(3,'Sem 3');
INSERT INTO semesters VALUES(4,'Sem 4');
INSERT INTO semesters VALUES(5,'Sem 5');
INSERT INTO semesters VALUES(6,'Sem 6');
CREATE TABLE `breaks` (`break_id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `break_type` TEXT NOT NULL, `break_start_time` TEXT NOT NULL, `break_end_time` TEXT NOT NULL);
INSERT INTO breaks VALUES(1,'TEA','10:50 AM','11:00 AM');
INSERT INTO breaks VALUES(2,'TEA','02:50 PM','03:00 PM');
INSERT INTO breaks VALUES(3,'LUNCH','01:00 PM','02:00 PM');
CREATE TABLE `programs` (`programs_id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `programs_code` TEXT NOT NULL, `programs_name` TEXT NOT NULL, `number_of_semesters` INTEGER NOT NULL);
INSERT INTO programs VALUES(1,'23-493','M.Voc in Software Application Development',4);
INSERT INTO programs VALUES(2,'20-493','M.Voc in Consultancy Management',4);
INSERT INTO programs VALUES(3,'20-491','B.Voc in Business Process and Data Analytics',6);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('user',1);
INSERT INTO sqlite_sequence VALUES('subjects',8);
INSERT INTO sqlite_sequence VALUES('instructors',4);
INSERT INTO sqlite_sequence VALUES('semesters',6);
INSERT INTO sqlite_sequence VALUES('breaks',3);
INSERT INTO sqlite_sequence VALUES('programs',3);
INSERT INTO sqlite_sequence VALUES('timetable',1);
CREATE INDEX `index_timetable_subject_id_instructor_id_programs_id_break_id_semester_id` ON `timetable` (`subject_id`, `instructor_id`, `programs_id`, `break_id`, `semester_id`);
CREATE INDEX `index_timetable_table_id` ON `timetable` (`table_id`);
CREATE INDEX `index_timetable_programs_id` ON `timetable` (`programs_id`);
CREATE INDEX `index_timetable_semester_id` ON `timetable` (`semester_id`);
CREATE INDEX `index_timetable_subject_id` ON `timetable` (`subject_id`);
CREATE INDEX `index_timetable_instructor_id` ON `timetable` (`instructor_id`);
CREATE INDEX `index_timetable_break_id` ON `timetable` (`break_id`);
CREATE INDEX `index_subjects_subject_id` ON `subjects` (`subject_id`);
CREATE INDEX `index_instructors_instructor_id` ON `instructors` (`instructor_id`);
CREATE INDEX `index_semesters_semester_id` ON `semesters` (`semester_id`);
CREATE INDEX `index_breaks_break_id` ON `breaks` (`break_id`);
CREATE INDEX `index_programs_programs_id` ON `programs` (`programs_id`);
CREATE INDEX `index_programs_programs_code` ON `programs` (`programs_code`);
COMMIT;